name: CI Pipeline

on:
  push:
    branches:
      - main  # Activa el pipeline cuando haya un push en la rama 'main'
  pull_request:
    branches:
      - main  # Activa el pipeline cuando se crea un PR hacia la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest
